### ISSUE TITLE
VRL-Studio ignores file argument on macOS

### ISSUE THREAD

**Issue by miho** [VRL-Studio/VRL-Studio#28]

**Comment by bsumirak** [comment]
This latest fix breaks my OS X application.
The main canvas window appears on startup, but is gray instead of the soothing gray-blue. Application remains unresponsive after that.
Starting using the run.sh on the command line gives no exceptions.

**Comment by miho** [comment]
That's strange. I will try on different macOS version to check whether I can reproduce it.
