### ISSUE TITLE
Dislocated notification object

### ISSUE THREAD

**Issue by bsumirak** [VRL-Studio/VRL-Studio#3]
I have not been able to find out when exactly this happens, but as it has occurred several times now, I decided to report it:

The object at the bottom of the canvas, that displays if there are any notifications, sometimes gets dislocated like in the screenshot below.

![scrsht](https://f.cloud.github.com/assets/6161119/1887185/2ea4c688-79f7-11e3-887d-7c812cf88c9a.png)

**Comment by miho** [comment]
Java 6 gives me the same behavior. I cannot reproduce the behavior with Java 8. Reopen the issue if you can still reproduce the behavior.
