### ISSUE TITLE
Chrome complains that https://vrl-studio.mihosoft.eu/ is not secure. 

### ISSUE THREAD

**Issue by alexander-poulikakos** [VRL-Studio/VRL-Studio#35]
![image](https://user-images.githubusercontent.com/16044466/95307076-7c5d5d00-0888-11eb-88ca-4e9fae79a339.png)

**Comment by stephanmg** [comment]
Hey @alexander-poulikakos, this is because of the indicated error: NET::ERR_CERT_DATE_INVALID

The Let's Encrypt certificate expired on Sep 25, 2020.

So I think you are safe for now. :)

**Comment by alexander-poulikakos** [comment]
any plans of updating the certificate?

**Comment by stephanmg** [comment]
> any plans of updating the certificate?

I presume so, but this is something @miho will be handling of course.

**Comment by miho** [comment]
Sorry for the inconvenience. The certificate will be updated in the next view days. The server infrastructure needs maintenance. We will increase the CPU/RAM because we saw a huge increase in users over the past month. The new server should be up and running end of the week.

**Comment by stephanmg** [comment]
Works for me.
