### ISSUE TITLE
"VRL-Studion.app" would like to record this computer's screen

### ISSUE THREAD

**Issue by alexander-poulikakos** [VRL-Studio/VRL-Studio#40]
Why does VRL-Studio want to record my screen?

![image](https://user-images.githubusercontent.com/16044466/109639695-c6a0ec80-7b4f-11eb-9738-88839307bb5f.png)

That popup keeps popping up even if I click "Deny".

**Comment by stephanmg** [comment]
Which version of VRL-Studio? I do not see this happening for me.

**Comment by alexander-poulikakos** [comment]
![image](https://user-images.githubusercontent.com/16044466/109681036-5c06a580-7b7d-11eb-9eca-cf82c958b951.png)

This wasn't happening to me before, but I upgraded my mac OS to Catalina (10.15.7) last week. That is when it started to happen.

**Comment by alexander-poulikakos** [comment]
I just realised that it's the Java code I have in my VRL plugin that tries to take a screenshot, which triggers a new Screen Recording permission in macOS, Starting with macOS Catalina.

More info here:
https://apple.stackexchange.com/questions/384228/how-do-i-configure-screen-recording-permission-on-macos-catalina 

Closing this issue.
