### ISSUE TITLE
VRL-Studio.app cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by alexander-poulikakos** [VRL-Studio/VRL-Studio#45]
I just upgraded my Mac to Big Sur and get this popup when trying to start VRL Studio IDE. Is there anything that can be done in VRL Studio to fix this?

![image](https://user-images.githubusercontent.com/16044466/122362934-d30f5080-cf58-11eb-9a96-3ad73d6f098f.png)

**Comment by stephanmg** [comment]
Hi, this is a common problem, you can just override it.

**Comment by alexander-poulikakos** [comment]
ok, thx!

**Comment by stephanmg** [comment]
I'm not using Mac too much anymore, but you can usually easily find it on the web how to override this. I  think we can trust @miho  :)
