### ISSUE TITLE
Loss of code editor scrollability after saving or compiling

### ISSUE THREAD

**Issue by bsumirak** [VRL-Studio/VRL-Studio#6]
When editing a piece of code that requires the code editor in VRL-Studio to have scrollbars, clicking the compile button or saving the project leads to deletion of all open windows in certain situations (I am not sure in which - possibly has something to do with interdependences between several groovy-implemented classes). These windows are then reloaded automatically. In the process, however, they loose their scrollbars and at the same time their scrollability. (Both can be recovered by resizing the code editor window.)

**Comment by miho** [comment]
Took a while to find the workaround. Feel free to reopen if it does not work for you.
